{
 "title": "Память и лимит",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Память и лимит",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"lab1\", container=\"api\"}",
     "legendFormat": "usage {{pod}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{namespace=\"lab1\", container=\"api\"}",
     "legendFormat": "limit {{pod}}"
    }
   ]
  },
  {
   "title": "CPU и квота",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"lab1\",\n    container=\"api\"\n  }[2m])\n)",
     "legendFormat": "usage {{pod}}"
    },
    {
     "expr": "container_spec_cpu_quota{namespace=\"lab1\", container=\"api\"}\n/\ncontainer_spec_cpu_period{namespace=\"lab1\", container=\"api\"}",
     "legendFormat": "quota {{pod}}"
    }
   ]
  },
  {
   "title": "CPU throttled: доля периодов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum by (pod) (\n  rate(container_cpu_cfs_throttled_periods_total{\n    namespace=\"lab1\",\n    container=\"api\"\n  }[2m])\n)\n/\nsum by (pod) (\n  rate(container_cpu_cfs_periods_total{\n    namespace=\"lab1\",\n    container=\"api\"\n  }[2m])\n)",
     "legendFormat": "throttled periods {{pod}}"
    }
   ]
  }
 ]
}